### ISSUE TITLE
Support incremental compression and decompression

### ISSUE THREAD

**Issue by davidmhammond** [kjdev/php-ext-brotli#26]
Although the brotli extension supports streaming via stream wrappers, it is currently missing the ability to compress/decompress incrementally. This feature is needed in order to achieve certain streaming workflows that cannot be accomplished with the existing functionality.

This would involve adding at least four new functions: `brotli_compress_init()`, `brotli_compress_add()`, `brotli_uncompress_init()`, and `brotli_uncompress_add()`. These functions should be analogous to the zlib extension's `deflate_init()`, `deflate_add()`, `inflate_init()`, and `inflate_add()`, respectively, including flags to control flush behavior (at a minimum, equivalents of `ZLIB_SYNC_FLUSH` and `ZLIB_FINISH`).

Example of when incremental compression is needed: You're using a response model such as PSR-7, the page output is generated in a streaming manner via a generator, and the response object contains headers indicating brotli compression. In this case, as you pull data from the response stream, that data should come out already brotli-compressed (this stream may or may not represent the final output to the browser). Currently, this can only be accomplished by compressing the entire stream contents at once (which means you don't get a true streaming pipeline), or by an elaborate hack whereby reading the stream writes to a brotli stream wrapper that is wrapped around a custom stream wrapper that writes to a buffer which the first stream then reads from. Support for incremental compression would make this much simpler and less hacky.

Example of when incremental decompression is needed: You're using a stream filter framework where each filter operates on a chunk of data at a time, and you want to create a filter that performs a brotli decompression of the input. With incremental decompression, the filter object could call `brotli_uncompress_init()` for the first chunk, and return `brotli_uncompress_add()` for each chunk in the stream, passing the `BROTLI_FINISH` flag on the final chunk. Without incremental decompression, there's really no way to accomplish brotli decompression in this kind of filter system without just building a giant string and decompressing it all on the final chunk (which, again, means you don't get a true streaming pipeline).

**Comment by kjdev** [comment]
Added a new function for simple incremental processing.

- `brotli_compress_init`
- `brotli_compress_init add`
- `brotli_uncompress_init`
- `brotli_uncompress_add`

sample.

``` php
// compression
$resource = brotli_compress_init();
$compressed = '';
$compressed .= brotli_compress_add($resource, 'Hello, ', BROTLI_PROCESS);
$compressed .= brotli_compress_add($resource, 'World!', BROTLI_PROCESS);
$compressed .= brotli_compress_add($resource, '', BROTLI_FINISH);

echo brotli_uncompress($compressed), PHP_EOL; // Hello, World!

// uncompression
$resource = brotli_uncompress_init();
$uncompressed = '';
$uncompressed .= brotli_uncompress_add($resource, substr($compressed, 0, 5), BROTLI_PROCESS);
$uncompressed .= brotli_uncompress_add($resource, substr($compressed, 5), BROTLI_PROCESS);
$uncompressed .= brotli_uncompress_add($resource, '', BROTLI_FINISH);

echo $uncompressed, PHP_EOL; // Hello, World!
```

**Comment by JakubOnderka** [comment]
Hello, I like the new functions for incremental compression! But I miss settings that are possible to set for `brotli_compress` method, but not possible for `brotli_compress_init`, like `quality` and `mode`. Will you consider to add these settings also for incremental compression? Thanks.

**Comment by kjdev** [comment]
a01f22e6812ecb0fb02bf77d5e4100f2fb493fe8 Added an argument to brotli_compress_init().

**Comment by kjdev** [comment]
What would be the case that it does not work properly?

``` php
<?php
// https://www.php.net/manual/en/function.deflate-add.php : Example

$handler = fopen('/tmp/test.csv', 'w');
// $deflateContext = deflate_init(ZLIB_ENCODING_GZIP, ['level' => 9]);
$brotliContext = brotli_compress_init();

$strings = [
  'Hello, how are you?' . PHP_EOL,
  'I am fine thanks' . PHP_EOL,
  'Hello, how are you?' . PHP_EOL,
];

foreach ($strings as $string) {
  // fwrite($handler, deflate_add($deflateContext, $string, ZLIB_NO_FLUSH));
  fwrite($handler, brotli_compress_add($brotliContext, $string, BROTLI_PROCESS));
}

// fwrite($handler, deflate_add($deflateContext, '', ZLIB_FINISH));
fwrite($handler, brotli_compress_add($brotliContext, '', BROTLI_FINISH));
fclose($handler);

// echo gzdecode(file_get_contents('/tmp/test.csv'));
echo brotli_uncompress(file_get_contents('/tmp/test.csv'));
```

**Comment by kjdev** [comment]
https://github.com/kjdev/php-ext-brotli/compare/master...develop

Is a correction like this sufficient?

**Comment by kjdev** [comment]
Is this correct?

https://github.com/kjdev/php-ext-brotli/commit/5e9353e67e515c12a3f6c2795b51391d2e86e5a5

``` c
while (available_in || BrotliEncoderHasMoreOutput(ctx->encoder)) {
  if (BrotliEncoderCompressStream(ctx->encoder,
  ..
}

if (mode == BROTLI_OPERATION_FINISH) {
    while (!BrotliEncoderIsFinished(ctx->encoder)) {
        if (BrotliEncoderCompressStream(ctx->encoder,
        ..
    }
}

```

**Comment by kjdev** [comment]
https://github.com/kjdev/php-ext-brotli/commit/0fefb0ef3f8344c7f3c290158537858d050ba3e2

```
TEST 4/28 [tests/compress_add.phpt]
PASS Test brotli_compress_add() functionality [tests/compress_add.phpt] 
```

The test will pass, so we will make adjustments based on this code.

**Comment by kjdev** [comment]
No blockers/questions so far
We will respond quickly

**Comment by kjdev** [comment]
Fixed (master branch)

A modified PECL version will be released later
