### ISSUE TITLE
php.ini or brotli.ini for extension=brotli.so

### ISSUE THREAD

**Issue by dilyanpalauzov** [kjdev/php-ext-brotli#31]
https://github.com/kjdev/php-ext-brotli#configuration says to put extension=brotli.so in brotli.ini, but it likely means php.ini.

**Comment by kjdev** [comment]
Yes, `php.ini` might be a better choice.

Redhat distribution's configuration was `/etc/php.d/***.ini`, so I had to adapt it to that.

**Comment by kjdev** [comment]
Fixed e92800fe00d2ecfdce38616b32d13805f5117817
