### ISSUE TITLE
How to install on a different version of php?

### ISSUE THREAD

**Issue by Dlunhappy226** [kjdev/php-ext-brotli#42]
I have many different version of php. It config at the wrong version of php. How can install at specific version of php?

**Comment by kjdev** [comment]
If you build and install the software in your environment, you should be able to use it.

``` bash
$ phpize
$ ./configure
$ make
$ make install
$ echo 'extension=brotli' > /path/to/php.d/brotli.ini
```

**Comment by Dlunhappy226** [comment]
I mean that I have php 8.1 install for default version but I want to install the extension for php version 7.4.

**Comment by kjdev** [comment]
Copy brotli.so built with PHP 7.4.

is not good enough?

**Comment by Dlunhappy226** [comment]
PHP Warning:  PHP Startup: brotli: Unable to initialize module
Module compiled with module API=20220829
PHP    compiled with module API=20190902
These options need to match
in Unknown on line 0

**Comment by Dlunhappy226** [comment]
I just forget to change the alternatives of `php-config`
